# Generated by Django 5.2.4 on 2025-08-19 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=191, unique=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_input', models.CharField(db_index=True, max_length=191)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.CharField(choices=[('all', 'All Modules'), ('passive', 'Passive Only'), ('footprint', 'Footprint'), ('investigate', 'Investigate')], default='all', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('modules_run', models.JSONField(blank=True, default=list)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('html_path', models.FileField(blank=True, null=True, upload_to='reports/html/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('modules_included', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_reports', to='core.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='ExploitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploit_name', models.CharField(db_index=True, max_length=191)),
                ('source', models.CharField(db_index=True, max_length=191)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploit_results', to='core.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='EnumerationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_results', to='core.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='VulnScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_name', models.CharField(db_index=True, max_length=191)),
                ('severity', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_results', to='core.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='ReconResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=191, null=True)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('raw_log', models.TextField()),
                ('tabular_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_results', to='core.scansession')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
        ),
        migrations.CreateModel(
            name='DigRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('TXT', 'TXT'), ('SOA', 'SOA'), ('PTR', 'PTR')], max_length=10)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('record_name', models.CharField(max_length=191)),
                ('record_data', models.CharField(max_length=512)),
                ('mx_priority', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dig_records', to='core.website')),
            ],
            options={
                'indexes': [models.Index(fields=['website', 'record_type'], name='core_digrec_website_2d6da0_idx')],
                'unique_together': {('website', 'record_type', 'record_name')},
            },
        ),
    ]
