# Generated by Django 5.2.4 on 2025-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='name',
            field=models.CharField(default='Default Scan', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scansession',
            name='profile',
            field=models.CharField(choices=[('all', 'All Modules'), ('passive', 'Passive Only'), ('footprint', 'Footprint'), ('investigate', 'Investigate')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='scansession',
            name='target_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
