# Generated by Django 5.2.5 on 2025-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scansession_name_scansession_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='modules_included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scansession',
            name='modules_run',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
