# Generated by Django 5.2.4 on 2025-08-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_finalreport_modules_included_scansession_modules_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('TXT', 'TXT'), ('SOA', 'SOA'), ('PTR', 'PTR')], max_length=10)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('record_name', models.CharField(max_length=255)),
                ('record_data', models.TextField()),
                ('mx_priority', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dig_records', to='core.website')),
            ],
            options={
                'indexes': [models.Index(fields=['website', 'record_type'], name='core_digrec_website_2d6da0_idx')],
            },
        ),
    ]
